export const positiveGroups = [
  "Bonus - Godt bonuskoncept",
  "Gaver - Gode gaver",
  "Generelt - Generelt godt/Generel glad kunde",
  "Kommunikation - God kommunikation/advisering",
  "Kundeservice - God service",
  "Kundeservice - Hurtig service",
  "Levering - Gode leveringsbetingelser",
  "Levering - Hurtig leveringstid",
  "Levering - Korrekt levering",
  "Lomax.dk - God hjemmeside/nem genbestilling/overskuelig",
  "Pris - Gode priser/Gode tilbud",
  "Sortiment - Godt miljøsortiment",
  "Sortiment - Godt/bredt/relevant sortiment/god kvalitet",
  "Økonomi - Gode betalingsbetingelser",
] as const;

export const negativeGroups = [
  "Bonus - Dårligt bonuskoncept",
  "Gaver - Drop gaver",
  "Gaver - Dårlige gaver",
  "Generelt - Generelt dårligt/Generel utilfreds kunde",
  "Kommunikation - Dårlig kommunikation/advisering/manglende kommunikation",
  "Kundeservice - Dårlig service",
  "Kundeservice - Langsom service",
  "Levering - Dårlig levering",
  "Levering - Dårlige leveringsbetingelser",
  "Levering - Forkert levering",
  "Levering - Lang leveringstid",
  "Levering - Mange leveringer",
  "Levering - Mange restordrer",
  "Levering - Ødelagt levering",
  "Lomax.dk - Dårlig hjemmeside (uoverskuelig)",
  "Nyhedsbrev - Dårlige/For mange nyhedsbreve",
  "Pris - Høje priser/dårlige tilbud",
  "Sortiment - Dårligt/smalt/irrelevant sortiment/dårlig kvalitet",
  "Økonomi - Dårlige betalingsbetingelser",
  "Økonomi - Utilfreds med miljøgebyr",
  "Pris - Fragtpris",
] as const;

export const neutralGroups = [
  "Bonus - Andet vedr. bonuskoncept",
  "Gaver - Andet vedr. gaver",
  "Gaver - Flere gaver",
  "Generelt - Andet vedr. generelt",
  "Kundeservice - Andet vedr. kundeservice",
  "Levering - Andet vedr. levering",
  "Lomax.dk - Andet vedr. hjemmeside",
  "Nyhedsbrev - Andet vedr. Nyhedsbreve",
  "Pris - Andet vedr. priser",
  "Sortiment - Andet vedr. Sortiment",
  "Økonomi - Andet vedr. økonomiafdeling",
] as const;

export const segmentationGroups = [
  ...positiveGroups,
  ...negativeGroups,
  ...neutralGroups,
] as const;
